services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: northstar-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.enable-lifecycle
    volumes:
      - ../prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../prometheus/rules:/etc/prometheus/rules:ro
      - ../prometheus/recording-rules:/etc/prometheus/recording-rules:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager
      - node-exporter
      - blackbox-exporter
      - cadvisor

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: northstar-alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
      - ../alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:11.1.4
    container_name: northstar-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: Northstar-Lab-Only-ChangeMe
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning:ro
      - ../grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: northstar-node-exporter
    command:
      - --path.rootfs=/host
    pid: host
    volumes:
      - /:/host:ro,rslave
    ports:
      - "9100:9100"

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: northstar-blackbox-exporter
    volumes:
      - ../blackbox-exporter/blackbox.yml:/config/blackbox.yml:ro
    command:
      - --config.file=/config/blackbox.yml
    ports:
      - "9115:9115"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: northstar-cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    ports:
      - "8081:8080"

volumes:
  prometheus_data:
  grafana_data:
