---
- name: Set enterprise timezone
  community.windows.win_timezone:
    timezone: "{{ timezone_id }}"
- name: Ensure baseline services are automatic and running
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: auto
    state: started
  loop: "{{ baseline_services }}"
- name: Configure Windows event log size
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\EventLog\System
    name: MaxSize
    data: "{{ audit_log_max_kb * 1024 }}"
    type: dword
