locals { name="${var.project_name}-${var.environment}"; tags={Project=var.project_name,Environment=var.environment,Owner="Cloud Operations",ManagedBy="Terraform"} }
resource "azurerm_resource_group" "main" { name="rg-${local.name}"; location=var.location; tags=local.tags }
resource "azurerm_virtual_network" "main" { name="vnet-${local.name}"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; address_space=["10.40.0.0/16"]; tags=local.tags }
resource "azurerm_subnet" "app" { name="snet-app"; resource_group_name=azurerm_resource_group.main.name; virtual_network_name=azurerm_virtual_network.main.name; address_prefixes=["10.40.10.0/24"] }
resource "azurerm_network_security_group" "app" { name="nsg-${local.name}-app"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; security_rule { name="AllowHTTP"; priority=100; direction="Inbound"; access="Allow"; protocol="Tcp"; source_port_range="*"; destination_port_range="80"; source_address_prefix="AzureLoadBalancer"; destination_address_prefix="*" }; tags=local.tags }
resource "azurerm_subnet_network_security_group_association" "app" { subnet_id=azurerm_subnet.app.id; network_security_group_id=azurerm_network_security_group.app.id }
resource "azurerm_public_ip" "lb" { name="pip-${local.name}-lb"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; allocation_method="Static"; sku="Standard"; tags=local.tags }
resource "azurerm_lb" "main" { name="lb-${local.name}"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; sku="Standard"; frontend_ip_configuration { name="frontend"; public_ip_address_id=azurerm_public_ip.lb.id }; tags=local.tags }
resource "azurerm_lb_backend_address_pool" "main" { name="backend"; loadbalancer_id=azurerm_lb.main.id }
resource "azurerm_lb_probe" "http" { name="http-health"; loadbalancer_id=azurerm_lb.main.id; protocol="Http"; port=80; request_path="/health" }
resource "azurerm_lb_rule" "http" { name="http"; loadbalancer_id=azurerm_lb.main.id; protocol="Tcp"; frontend_port=80; backend_port=80; frontend_ip_configuration_name="frontend"; backend_address_pool_ids=[azurerm_lb_backend_address_pool.main.id]; probe_id=azurerm_lb_probe.http.id }
resource "random_password" "admin" { length=24; special=true }
resource "azurerm_network_interface" "vm" { name="nic-${local.name}-01"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; ip_configuration { name="internal"; subnet_id=azurerm_subnet.app.id; private_ip_address_allocation="Dynamic" }; tags=local.tags }
resource "azurerm_network_interface_backend_address_pool_association" "vm" { network_interface_id=azurerm_network_interface.vm.id; ip_configuration_name="internal"; backend_address_pool_id=azurerm_lb_backend_address_pool.main.id }
resource "azurerm_linux_virtual_machine" "vm" { name="vm-${local.name}-01"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; size="Standard_B1s"; admin_username=var.admin_username; admin_password=random_password.admin.result; disable_password_authentication=false; network_interface_ids=[azurerm_network_interface.vm.id]; os_disk { caching="ReadWrite"; storage_account_type="Standard_LRS"; disk_encryption_set_id=null }; source_image_reference { publisher="Canonical"; offer="0001-com-ubuntu-server-jammy"; sku="22_04-lts-gen2"; version="latest" }; custom_data=base64encode("#!/bin/bash
apt-get update
apt-get install -y nginx
echo healthy >/var/www/html/health
systemctl enable --now nginx
"); identity { type="SystemAssigned" }; tags=local.tags }
resource "azurerm_log_analytics_workspace" "main" { name="law-${local.name}"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; sku="PerGB2018"; retention_in_days=30; tags=local.tags }
resource "azurerm_monitor_action_group" "ops" { name="ag-${local.name}"; resource_group_name=azurerm_resource_group.main.name; short_name="opsalert"; tags=local.tags }
resource "azurerm_monitor_metric_alert" "cpu" { name="High CPU - ${local.name}"; resource_group_name=azurerm_resource_group.main.name; scopes=[azurerm_linux_virtual_machine.vm.id]; description="CPU above 80 percent for 10 minutes"; severity=2; frequency="PT5M"; window_size="PT10M"; criteria { metric_namespace="Microsoft.Compute/virtualMachines"; metric_name="Percentage CPU"; aggregation="Average"; operator="GreaterThan"; threshold=80 }; action { action_group_id=azurerm_monitor_action_group.ops.id }; tags=local.tags }
resource "azurerm_key_vault" "main" { name=substr(replace("kv-${local.name}","-",""),0,24); location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; tenant_id=data.azurerm_client_config.current.tenant_id; sku_name="standard"; soft_delete_retention_days=7; purge_protection_enabled=true; enable_rbac_authorization=true; tags=local.tags }
data "azurerm_client_config" "current" {}
resource "azurerm_recovery_services_vault" "main" { name="rsv-${local.name}"; location=azurerm_resource_group.main.location; resource_group_name=azurerm_resource_group.main.name; sku="Standard"; storage_mode_type="LocallyRedundant"; soft_delete_enabled=true; tags=local.tags }
resource "azurerm_backup_policy_vm" "daily" { name="daily-30-day"; resource_group_name=azurerm_resource_group.main.name; recovery_vault_name=azurerm_recovery_services_vault.main.name; timezone="UTC"; backup { frequency="Daily"; time="03:00" }; retention_daily { count=30 } }
resource "azurerm_backup_protected_vm" "vm" { resource_group_name=azurerm_resource_group.main.name; recovery_vault_name=azurerm_recovery_services_vault.main.name; source_vm_id=azurerm_linux_virtual_machine.vm.id; backup_policy_id=azurerm_backup_policy_vm.daily.id }
