all:
  children:
    lab_canary:
      hosts:
        WEB01:
          ansible_host: 10.20.30.31
    domain_controllers:
      hosts:
        DC01: { ansible_host: 10.20.30.10 }
        DC02: { ansible_host: 10.20.30.11 }
    file_servers:
      hosts:
        FS01: { ansible_host: 10.20.30.20 }
        FS02: { ansible_host: 10.20.30.21 }
    web_servers:
      hosts:
        WEB01: { ansible_host: 10.20.30.31 }
        WEB02: { ansible_host: 10.20.30.32 }
    operations_servers:
      hosts:
        MON01: { ansible_host: 10.20.30.40 }
        BAK01: { ansible_host: 10.20.30.50 }
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: validate
    ansible_user: NORTHSTAR\svc_ansible
